services:
  deepseek-web-to-api:
    build: .
    container_name: deepseek-web-to-api
    ports:
      - "4981:4981"
    env_file:
      - .env
    volumes:
      - ./cookies:/app/cookies
    restart: unless-stopped
